### ISSUE TITLE
spektrum fails to start; java error

### ISSUE THREAD

**Issue by challengersky** [pavels/spektrum#42] opened 2021-12-20 16:19 UTC
After installing spektrum, when I start it I get the following error:  "./spektrum: 5: ./spektrum: /home/pi/Documents/Spektrum/spektrum/java/bin/java: Exec format error"

My java version:  "openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Raspbian-2deb10u1)
OpenJDK Server VM (build 11.0.12+7-post-Raspbian-2deb10u1, mixed mode)"

Hardware:  Raspberry Pi 4B, latest Raspbian OS 32-bit fully updated/upgraded.

Any help getting past this error is very much appreciated.

**Comment by pavels** [comment] 2021-12-22 02:16
There are binary parts compiled for x86 architecture - it will not work on Pi as is unfortunatelly

**Comment by pavels** [comment] 2022-01-06 19:49
Duplicate of https://github.com/pavels/spektrum/issues/39

**Closed as completed by pavels** 2022-01-06 19:49 UTC
