### ISSUE TITLE
Gray window, nothing else

### ISSUE THREAD

**Issue by dalbert2** [pavels/spektrum#9] opened 2017-11-13 20:13 UTC
Windows 10 x64, RTL-SDR dongle, used zadig to install winusb driver.  Dongle works perfectly with SDR# but when launching 1.0.1 or 1.0.2, spekctrum window just has the title bar and a gray background.  Clicking on title yields an error dialog: Can't open rtl-sdr device, then the app closes.  VC++ re-distributable 2012 is installed.

**Comment by pavels** [comment] 2018-02-13 14:18
duplicate of this - https://github.com/pavels/spektrum/issues/8 lets discuss there

**Closed as completed by pavels** 2018-02-13 14:18 UTC
