### ISSUE TITLE
Can not open RTL sdr device on startup

### ISSUE THREAD

**Issue by wa3tfs** [pavels/spektrum#8] opened 2017-10-15 19:31 UTC
I get error when trying to open program.  Running win 10 64 bit on laptop.  I use the dongle on HDSDR and SDR# with no problem but it will not work with this program for some reason.  Any ideas?

**Comment by willydp** [comment] 2017-11-28 11:47
Same problem here: Gray screen at startup and message can't connect device:
RTL SDR working fine in other programs and Visual ++ 64 is installed.
No one??????

**Comment by radiojitter** [comment] 2017-12-23 17:54
yes , i have same issue

**Comment by iotlearner0level** [comment] 2018-02-10 18:37
same problem here.

**Comment by pavels** [comment] 2018-02-13 14:18
Hi
unfortunately i have very little time for this project now - gray screen means that something crashed during initialization - the only way to debug this is to install processing, open the project there and run it, you will have console with exceptions there and you will see some errors
If somebody can provide me with some exception log, i can take a look, without anything it is hard for me to debug

**Comment by iotlearner0level** [comment] 2018-02-14 21:51
i've spent some more time with this. looks like there are two rtlsdr devices listed #0 a bogus one and #1 the real hardware. rtlsharp selects the correct one... commandline utility also lists two devices. maybe that could be the cause.

**Comment by pavels** [comment] 2018-02-14 22:26
Hmm so we would need the device selection - i will try to find some time and add some way to select which device is used

**Comment by RCZevallos** [comment] 2018-02-15 17:41
Pavel. Please i will appreciate if you also let Spektrum to work further than 2.147 GHz. At least up to 2.3 GHz to work with the NESDR XTR+ dongle.  Thanks in advance.

NB: I have the same message "Can´t open rtl-sdr device" on Windows 10 64 bits.  SDR# and Touchtone works fine in the same laptop.

**Comment by tdbone1** [comment] 2018-03-25 22:45
could really use that device selection please.

**Comment by pavels** [comment] 2018-03-26 23:18
Device selection done

BTW on Win10 - if you get can't open device, get zadiag and reinstall winusb for your dongle

**Comment by girogiacomo** [comment] 2018-05-18 20:18
Hi, it's my first post on GitHub, so tell me if I'm breaking some rules :D 
I've tried your software both on windows 10 and windows 7 and on w7 it works perfectly fine but in w10, i'm able to select the device throw the library swap tib but i'm still unable to access the device because when I select one of the two devices (why 2.. I've a single SDR dondle...) I'm unable to get it work because appears a warning message.... If I try to select the other device, same story....
![immagine](https://user-images.githubusercontent.com/39419444/40256057-84adf1a8-5ae9-11e8-91a7-dc3a59aec20b.png)
Very thanks for this amazing project and best of luck! (Sorry for my poor english :))

**Comment by wa3tfs** [comment] 2018-05-18 20:44
I had the same problem, downloaded the latest software version and re-installed Zadig and it now works.

**Comment by radiojitter** [comment] 2018-05-19 03:03
I had same issue, I downloaded latest version of Zadig ( mine is 64 bit)
,re installed the Zadig ,reinstslled the rtl SDR kernel driver, now
spectrum is working fine. I wanted to use it for swr measurement , anyway
it works good as simple spectrum analyser.
Regards
Priyasloka Arya

**Comment by kghill** [comment] 2018-11-12 13:59
Hi All:
On my computer I have had success running version 1.0.2 of Spectrum on Windows 10 64 bit. What I have done is:
1). put the Spectrum folder on my desktop, 
2) Shutdown all other apps and turned off my WiFi and bluetooth. (I have had to do this with other apps.. I think my computer runs a little slow).
3) Unplug all other USB devices
4) plug in my RTL-SDR Usb device and check in device manager that it is recognized. 
5) Launch Spectrum. It will come up with a grey screen and a few seconds later the screen comes up.

So far I have analyzed two antennas using the above method. (See enclosed)

I would to thank the author for the work he has done on this project. 

![1qtr wave ground plian](https://user-images.githubusercontent.com/32202796/48352665-92395780-e64a-11e8-9d36-ee578a4773d4.JPG)

**Comment by tjt263** [comment] 2019-01-17 06:54
# Debian

### Error:
<pre><code><b>user@debian:~$</b> ~/Desktop/spektrum/spektrum 

Loading libs from /user/Desktop/spektrum/lib.
Library rtlsdr file /user/Desktop/spektrum/lib/librtlsdr.so.
Library rtlpower file /user/Desktop/spektrum/lib/librtlpower.so.
Generic RTL2832U OEM
ControlP5 2.2.5 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
Reached end of setup.
Loading libs from /user/Desktop/spektrum/lib.
Library rtlsdr file /user/Desktop/spektrum/lib/librtlsdr.so.
Library rtlpower file /user/Desktop/spektrum/lib/librtlpower.so.

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
File /user/Desktop/spektrum/data/config.csv
File /user/Desktop/spektrum/data/config.csv exists.
Reached end of makeconfig
Config table config.csv loaded.
startFreq = 88000000 stopFreq = 108000000 binStep = 1000 scaleMin = -110 scaleMax =  40 vertCusorFreq = 88000000
</code></pre>

### Workaround:
<pre><code>rmmod -f dvb_usb_rtl28xxu
rmmod -f dvb_usb_v2
rmmod -f rc_core
</code></pre>

**Comment by laurencedv** [comment] 2020-05-26 21:46
same problem as @tjt263 mentionned in LM19.3 (ubuntu 18.04 based) basicly just ensure the rtl_sdr module is the only one currently active for the dongle.

Thanks to @pavels and @tjt263

**Comment by rag2** [comment] 2020-05-26 22:12
On Ubuntu 18.04 system with standard repository librtlsdr, unloading kernel modules didn't help, since repository **librtlsdr** kept seizing the dongle when plugged in, and wouldn't release the dvb_usb_rtl28xxu module when plugged in.

However, using **VirtualBox** (plus extension pack and guest additions) worked with a VM consisting of vanilla Ubuntu 18.04 plus Spektrum install, including setting a USB filter to seize the RTL-SDR USB. (Loading an OS in to a VM (virtual machine) was very fast, so easy to set up!) Then the modified librtlsdr takes control of the RTL-SDR dongle and all seems to work as it should.

**Comment by pavels** [comment] 2020-05-26 23:43
@rag2 there is some output to the console when spektrum is started from command line - can you pleas post this output? Looks like the wrong version of the librtlsdr is picked up - that should have been fixed in latest version but maybe a messed something up

**Closed as completed** 2021-01-04 11:05 UTC
